# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  SFML_System_config = debug
  SFML_Graphics_config = debug
  SFML_Window_config = debug
  SFML_Audio_config = debug
  SFML_Network_config = debug
  SFML_Main_config = debug
endif
ifeq ($(config),release)
  SFML_System_config = release
  SFML_Graphics_config = release
  SFML_Window_config = release
  SFML_Audio_config = release
  SFML_Network_config = release
  SFML_Main_config = release
endif

PROJECTS := SFML-System SFML-Graphics SFML-Window SFML-Audio SFML-Network SFML-Main

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

SFML-System:
ifneq (,$(SFML_System_config))
	@echo "==== Building SFML-System ($(SFML_System_config)) ===="
	@${MAKE} --no-print-directory -C . -f SFML-System.make config=$(SFML_System_config)
endif

SFML-Graphics:
ifneq (,$(SFML_Graphics_config))
	@echo "==== Building SFML-Graphics ($(SFML_Graphics_config)) ===="
	@${MAKE} --no-print-directory -C . -f SFML-Graphics.make config=$(SFML_Graphics_config)
endif

SFML-Window:
ifneq (,$(SFML_Window_config))
	@echo "==== Building SFML-Window ($(SFML_Window_config)) ===="
	@${MAKE} --no-print-directory -C . -f SFML-Window.make config=$(SFML_Window_config)
endif

SFML-Audio:
ifneq (,$(SFML_Audio_config))
	@echo "==== Building SFML-Audio ($(SFML_Audio_config)) ===="
	@${MAKE} --no-print-directory -C . -f SFML-Audio.make config=$(SFML_Audio_config)
endif

SFML-Network:
ifneq (,$(SFML_Network_config))
	@echo "==== Building SFML-Network ($(SFML_Network_config)) ===="
	@${MAKE} --no-print-directory -C . -f SFML-Network.make config=$(SFML_Network_config)
endif

SFML-Main:
ifneq (,$(SFML_Main_config))
	@echo "==== Building SFML-Main ($(SFML_Main_config)) ===="
	@${MAKE} --no-print-directory -C . -f SFML-Main.make config=$(SFML_Main_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f SFML-System.make clean
	@${MAKE} --no-print-directory -C . -f SFML-Graphics.make clean
	@${MAKE} --no-print-directory -C . -f SFML-Window.make clean
	@${MAKE} --no-print-directory -C . -f SFML-Audio.make clean
	@${MAKE} --no-print-directory -C . -f SFML-Network.make clean
	@${MAKE} --no-print-directory -C . -f SFML-Main.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   SFML-System"
	@echo "   SFML-Graphics"
	@echo "   SFML-Window"
	@echo "   SFML-Audio"
	@echo "   SFML-Network"
	@echo "   SFML-Main"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"